spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin         
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh #暴露bus-refresh刷新端点      
    
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka  #默认位置，可以修改为具体地理位置，比如：beiJing, shangHai, shenZhen 等，表示 eureka 服务器的部署位置
#---
#spring:
#  profiles: item1
  
#server:
#  port: 8001
#---
#spring:
#  profiles: item2

#server:
#  port: 8002