spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin         
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh #暴露bus-refresh刷新端点
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka #默认位置，可以修改为具体地理位置，比如：beiJing, shangHai, shenZhen 等，表示 eureka 服务器的部署位置
  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip
feign:
  hystrix:
    enabled: true #启用hystrix      


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,bus-refresh   